language: ruby
bundler_args: --without development
rvm:
  - ruby-head
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3
os:
  - linux
  # - osx
cache: bundler
sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
env: TEST=true
before_install: git submodule update --init --recursive
script: bundle exec rake test
notifications:
  slack: middleman:JW9OvXmn1m3XrSERe8866nBR